In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [12]:
train=pd.read_csv(r'D:/Desktop/ML project final/train (3).csv', nrows=1800)
test=pd.read_csv(r'D:/Desktop/ML project final/test (1).csv', nrows=500)

In [13]:
train

,id,title,author,text,label
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1
...,...,...,...,...,...
1795,1795,French Voting Station Reopens After Security S...,Breitbart London,PARIS (AP) — A voting station in eastern Fr...,0
1796,1796,Immigration Hawks Ascend to Senior DHS Positions,John Binder,Two leading advocates for reforming illegal an...,0
1797,1797,Running of the Sheep 2016: Black Friday “Getti...,Mac Slavo,\nBlack Friday madness has reached one of its ...,1
1798,1798,725 Days To Nowhere—A Stock Market Inhabited B...,David Stockman,725 Days To Nowhere---A Stock Market Inhabited...,1
1799,1799,Massive Pillow Fight in Downtown Los Angeles o...,Adelle Nazarian,"Hundreds of children, teens, adults and senior...",0

In [14]:
test

,id,title,author,text
0,20800,"Specter of Trump Loosens Tongues, if Not Purse...",David Streitfeld,"PALO ALTO, Calif. — After years of scorning..."
1,20801,Russian warships ready to strike terrorists ne...,NaN,Russian warships ready to strike terrorists ne...
2,20802,#NoDAPL: Native American Leaders Vow to Stay A...,Common Dreams,Videos #NoDAPL: Native American Leaders Vow to...
3,20803,"Tim Tebow Will Attempt Another Comeback, This ...",Daniel Victor,"If at first you don’t succeed, try a different..."
4,20804,Keiser Report: Meme Wars (E995),Truth Broadcast Network,42 mins ago 1 Views 0 Comments 0 Likes 'For th...
...,...,...,...,...
495,21295,Orlando Police Defend Actions as Clock Ticked ...,"Richard Pérez-Peña, Frances Robles and Eric Li...",Some details of the Orlando nightclub massacre...
496,21296,"‘I’m Nobody’? Not a Chance, Emily Dickinson - ...",Holland Cotter,"“In the Trumpian sense of the term, she’s the ..."
497,21297,New NASA Footage Films UFO Flying Past,BlackProject,New NASA Footage Films UFO Flying Past page: 1...
498,21298,Obamacare Architect on Rising Premiums: It’s N...,admin,"Washington Free Beacon October 26, 2016 \nDr. ..."
499,21299,QUALIFIED! Joe Biden explains reason Hillary s...,Posted At Am On October,QUALIFIED! Joe Biden explains reason Hillary s...

In [15]:
test=test.fillna(' ')
train=train.fillna(' ')
test['total']=test['title']+' '+test['author']+test['text']
train['total']=train['title']+' '+train['author']+train['text']

In [16]:
train.head()

,id,title,author,text,label,total
0,0,House Dem Aide: We Didn’t Even See Comey’s Let...,Darrell Lucus,House Dem Aide: We Didn’t Even See Comey’s Let...,1,House Dem Aide: We Didn’t Even See Comey’s Let...
1,1,"FLYNN: Hillary Clinton, Big Woman on Campus - ...",Daniel J. Flynn,Ever get the feeling your life circles the rou...,0,"FLYNN: Hillary Clinton, Big Woman on Campus - ..."
2,2,Why the Truth Might Get You Fired,Consortiumnews.com,"Why the Truth Might Get You Fired October 29, ...",1,Why the Truth Might Get You Fired Consortiumne...
3,3,15 Civilians Killed In Single US Airstrike Hav...,Jessica Purkiss,Videos 15 Civilians Killed In Single US Airstr...,1,15 Civilians Killed In Single US Airstrike Hav...
4,4,Iranian woman jailed for fictional unpublished...,Howard Portnoy,Print \nAn Iranian woman has been sentenced to...,1,Iranian woman jailed for fictional unpublished...

In [17]:
test.head()

,id,title,author,text,total
0,20800,"Specter of Trump Loosens Tongues, if Not Purse...",David Streitfeld,"PALO ALTO, Calif. — After years of scorning...","Specter of Trump Loosens Tongues, if Not Purse..."
1,20801,Russian warships ready to strike terrorists ne...,,Russian warships ready to strike terrorists ne...,Russian warships ready to strike terrorists ne...
2,20802,#NoDAPL: Native American Leaders Vow to Stay A...,Common Dreams,Videos #NoDAPL: Native American Leaders Vow to...,#NoDAPL: Native American Leaders Vow to Stay A...
3,20803,"Tim Tebow Will Attempt Another Comeback, This ...",Daniel Victor,"If at first you don’t succeed, try a different...","Tim Tebow Will Attempt Another Comeback, This ..."
4,20804,Keiser Report: Meme Wars (E995),Truth Broadcast Network,42 mins ago 1 Views 0 Comments 0 Likes 'For th...,Keiser Report: Meme Wars (E995) Truth Broadcas...

In [18]:
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re

ps = PorterStemmer()
stop_words = set(stopwords.words('english'))
regex = re.compile('[^a-zA-Z]')

corpus = []
for i in range(len(train)):
    review = regex.sub(' ', train['total'][i])
    review = review.lower().split()
    review = [ps.stem(word) for word in review if word not in stop_words]
    corpus.append(' '.join(review))

count_vectorizer = CountVectorizer(ngram_range=(1, 2))
counts = count_vectorizer.fit_transform(corpus)
transformer = TfidfTransformer(smooth_idf=False)
tfidf = transformer.fit_transform(counts)

In [20]:

targets = train['label'].values

In [21]:

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(tfidf, targets, random_state=0)

# Multinominal NB

In [22]:
from sklearn.naive_bayes import MultinomialNB

NB = MultinomialNB()
NB.fit(X_train, y_train)
print('Accuracy of NB  classifier on training set: {:.2f}'
     .format(NB.score(X_train, y_train)))
print('Accuracy of NB classifier on test set: {:.2f}'
     .format(NB.score(X_test, y_test)))

Accuracy of NB  classifier on training set: 0.98
Accuracy of NB classifier on test set: 0.72

# Random Forest

In [24]:
from sklearn.ensemble import RandomForestClassifier
RnFr = RandomForestClassifier()
RnFr.fit(X_train, y_train)
print('Accuracy of RandomForest classifier on training set: {:.2f}'
     .format(RnFr.score(X_train, y_train)))
print('Accuracy of RandomForest classifier on test set: {:.2f}'
     .format(RnFr.score(X_test, y_test)))

Accuracy of RandomForest classifier on training set: 1.00
Accuracy of RandomForest classifier on test set: 0.90

# SVM

In [25]:
from sklearn.svm import SVC
svclassifier = SVC(C=1,kernel='linear',gamma = 'auto',probability=True)
svclassifier.fit(X_train, y_train)
print('Accuracy of SVM classifier on training set: {:.2f}'
     .format(RnFr.score(X_train, y_train)))
print('Accuracy of SVM classifier on test set: {:.2f}'
     .format(RnFr.score(X_test, y_test)))

Accuracy of SVM classifier on training set: 1.00
Accuracy of SVM classifier on test set: 0.90

# AdaBoostClassifier

In [26]:
from sklearn.ensemble import AdaBoostClassifier
ada_classifier= AdaBoostClassifier()
ada_classifier.fit(X_train, y_train)
print('Accuracy of AdaBoostClassifier classifier on training set: {:.2f}'
     .format(RnFr.score(X_train, y_train)))
print('Accuracy of AdaBoostClassifier classifier on test set: {:.2f}'
     .format(RnFr.score(X_test, y_test)))

c:\Users\Parth\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

Accuracy of AdaBoostClassifier classifier on training set: 1.00
Accuracy of AdaBoostClassifier classifier on test set: 0.90

# LogisticRegression

In [27]:
from sklearn.linear_model import LogisticRegression
log_classifier=LogisticRegression()
log_classifier.fit(X_train, y_train)
print('Accuracy of LogisticRegression classifier on training set: {:.2f}'
     .format(RnFr.score(X_train, y_train)))
print('Accuracy of LogisticRegression classifier on test set: {:.2f}'
     .format(RnFr.score(X_test, y_test)))

Accuracy of LogisticRegression classifier on training set: 1.00
Accuracy of LogisticRegression classifier on test set: 0.90